version: '3'

services:
  proxy:
    image: envoyproxy/envoy:v1.26-latest
    ports:
      - "8000:8000"
      - "9901:9901"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    command: [ "envoy", "-c", "/etc/envoy/envoy.yaml" ]

  products:
    image: erikwegner/rsecho
    ports:
      - "3000:3000"

  sellers:
    image: erikwegner/rsecho
    ports:
      - "3001:3000"

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  ratelimit:
    image: envoyproxy/ratelimit:master
    command: /bin/ratelimit
    ports:
      - 8080:8080
      - 8081:8081
      - 6070:6070
    depends_on:
      - redis
      - proxy
    volumes:
      - ./ratelimit:/data/ratelimit/config
    environment:
      - USE_STATSD=false
      - LOG_LEVEL=debug
      - REDIS_SOCKET_TYPE=tcp
      - REDIS_URL=redis:6379
      - RUNTIME_ROOT=/data
      - RUNTIME_SUBDIRECTORY=ratelimit
      - RUNTIME_WATCH_ROOT=false
      - CONFIG_TYPE=${CONFIG_TYPE:-FILE}
